# RabbitMQ::BLM
BROKER_HOST = "64.207.159.216"
BROKER_PORT = 5672
BROKER_USER = "blm"
BROKER_PASSWORD = "m0nkeP4w7"
BROKER_VHOST = "blmvhost"

# Celery
CELERY_RESULT_BACKEND = "amqp"
CELERY_AMQP_TASK_RESULT_EXPIRES = 60