def v_0_2_routing(config):
    # User
    config.add_route('02-user-collection',              '/0.2/users')
    config.add_route('02-user-details',                 '/0.2/users/{user_id:\d+}')
    config.add_route('02-user-accounts',                '/0.2/users/{user_id:\d+}/accounts')
    config.add_route('02-user-tickets',                 '/0.2/users/{user_id:\d+}/tickets')
    config.add_route('02-user-orders',                  '/0.2/users/{user_id:\d+}/orders')
    config.add_route('02-user-mails-activation',        '/0.2/users/{user_id:\d+}/mails/activation')
    config.add_route('02-user-mails-recovery',          '/0.2/users/{user_id:\d+}/mails/recovery')
    config.add_route('02-user-password',                '/0.2/users/{user_id:\d+}/password/{password}')
    # Account
    config.add_route('02-account-collection',           '/0.2/accounts')
    config.add_route('02-account-own-details',          '/0.2/accounts/me')
    config.add_route('02-account-resource',             '/0.2/accounts/{account_id:[0-9A-Za-z]+}')
    config.add_route('02-account-keys',                 '/0.2/accounts/{account_id:[0-9A-Za-z]+}/keys')
    config.add_route('02-account-statistics',           '/0.2/accounts/{account_id:[0-9A-Za-z]+}/statistics')
    config.add_route('02-account-statistics-customers', '/0.2/accounts/{account_id:[0-9A-Za-z]+}/statistics/customers')
    config.add_route('02-account-statistics-monthly',   '/0.2/accounts/{account_id:[0-9A-Za-z]+}/statistics/monthly')
    config.add_route('02-account-events',               '/0.2/accounts/{account_id:[0-9A-Za-z]+}/events')
    config.add_route('02-account-locations',            '/0.2/accounts/{account_id:[0-9A-Za-z]+}/locations')
    config.add_route('02-account-visitors',             '/0.2/accounts/{account_id:[0-9A-Za-z]+}/visitors')
    config.add_route('02-account-psp',                  '/0.2/accounts/{account_id:[0-9A-Za-z]+}/psp')
    config.add_route('02-account-orders-collection',    '/0.2/accounts/{account_id:[0-9A-Za-z]+}/orders')
    config.add_route('02-account-extensions',    		'/0.2/accounts/{account_id:[0-9A-Za-z]+}/extensions')
    # Orders
    config.add_route('02-orders',                       '/0.2/orders')
    config.add_route('02-orders-started-detail',        '/0.2/orders/started/{order_key}')
    config.add_route('02-orders-detail',                '/0.2/orders/{order_key}')
    # Location
    config.add_route('02-location-collection',          '/0.2/locations')
    config.add_route('02-location-details',             '/0.2/locations/{location_id:\d+}')
    # Event
    config.add_route('02-event-list',                   '/0.2/events')
    config.add_route('02-event-resource',               '/0.2/events/{event_id:\d+}')
    config.add_route('02-event-tickettypes',            '/0.2/events/{event_id:\d+}/tickettypes')
    config.add_route('02-event-parts',                  '/0.2/events/{event_id:\d+}/eventparts')
    config.add_route('02-event-tickets',                '/0.2/events/{event_id:\d+}/tickets')
    config.add_route('02-event-orders',                 '/0.2/events/{event_id:\d+}/orders')
    config.add_route('02-event-statistics',             '/0.2/events/{event_id:\d+}/statistics')
    config.add_route('02-event-visitors',               '/0.2/events/{event_id:\d+}/visitors')
    config.add_route('02-event-locations',              '/0.2/events/{event_id:\d+}/locations')
    # Parts
    config.add_route('02-parts-tickettypes',            '/0.2/eventparts/{eventpart_id:\d+}/tickettypes')
    config.add_route('02-parts-resource',               '/0.2/eventparts/{eventpart_id:\d+}')
    
    # Tickettype
    config.add_route('02-tickettype-resource',          '/0.2/tickettypes/{tickettype_id:\d+}')
    # Payment Provider
    config.add_route('02-psp-notify',                   '/0.2/psp/{psp_id:\d+}/notify')
    # Ticket
    config.add_route('02-ticket-details',               '/0.2/tickets/{ticket_code:[0-9A-Fa-f]+}')
    config.add_route('02-ticket-scans',                 '/0.2/tickets/{ticket_code:[0-9A-Fa-f]+}/scans')
    config.add_route('02-ticket-mail',                  '/0.2/tickets/{ticket_code:[0-9A-Fa-f]+}/mail')
    config.add_route('02-ticket-reset-scans',           '/0.2/tickets/resetscans')
    return config