def v_0_1_routing(config):
    # User
    config.add_route('01-user-collection',              '/0.1/users')
    config.add_route('01-user-create',                  '/0.1/users/create')
    config.add_route('01-user-authenticate',            '/0.1/users/authenticate')
    config.add_route('01-user-details',                 '/0.1/users/{user_id:\d+}')
    config.add_route('01-user-activate',                '/0.1/users/{user_id:\d+}/activate')
    config.add_route('01-user-tickets',                 '/0.1/users/{user_id:\d+}/tickets')
    config.add_route('01-user-orders',                  '/0.1/users/{user_id:\d+}/orders')
    config.add_route('01-user-exists',                  '/0.1/users/exists')
    # Account
    config.add_route('01-account-collection',           '/0.1/accounts')
    config.add_route('01-account-resource',             '/0.1/accounts/{account_id:\d+}')
    config.add_route('01-account-create',               '/0.1/accounts/create')
    config.add_route('01-account-own-details',          '/0.1/accounts/me')
    config.add_route('01-account-events',               '/0.1/accounts/{account_id:\d+}/events')
    config.add_route('01-account-addpsp',               '/0.1/accounts/{account_id:\d+}/addpsp')
    # Location
    config.add_route('01-location-list',                '/0.1/locations')
    config.add_route('01-location-create',              '/0.1/locations/create')
    config.add_route('01-location-search',              '/0.1/locations/search')
    config.add_route('01-location-details',             '/0.1/locations/{location_id:\d+}')
    # Event
    config.add_route('01-event-list',                   '/0.1/events') # undocumented
    config.add_route('01-event-resource',               '/0.1/events/{event_id:\d+}')
    config.add_route('01-event-create',                 '/0.1/events/create')
    config.add_route('01-event-tickettypes',            '/0.1/events/{event_id:\d+}/tickettypes')
    config.add_route('01-event-tickets',                '/0.1/events/{event_id:\d+}/tickets')
    config.add_route('01-event-statistics',             '/0.1/events/{event_id:\d+}/statistics')
    config.add_route('01-event-access',                 '/0.1/events/{event_id:\d+}/access')
    config.add_route('01-event-addpart',                '/0.1/events/{event_id:\d+}/addpart')
    # Tickettype
    config.add_route('01-tickettype-create',            '/0.1/tickettypes/create')
    config.add_route('01-tickettype-resource',          '/0.1/tickettypes/{tickettype_id:\d+}')
    # Order
    config.add_route('01-order-new',                    '/0.1/orders/add')
    config.add_route('01-order-add',                    '/0.1/orders/{order_key}/add')
    config.add_route('01-order-checkout',               '/0.1/orders/{order_key}/checkout')
    config.add_route('01-order-mail',                   '/0.1/orders/{order_key}/mail')
    config.add_route('01-order-details',                '/0.1/orders/{order_key}')
    # Payment Provider
    config.add_route('01-psp-notify',                   '/0.1/psp/{psp_id:\d+}/notify')
    # Ticket
    config.add_route('01-ticket-details',               '/0.1/tickets/{ticket_code:[0-9A-Fa-f]+}')
    config.add_route('01-ticket-scan',                  '/0.1/tickets/{ticket_code:[0-9A-Fa-f]+}/scan')
    config.add_route('01-ticket-mail',                  '/0.1/tickets/{ticket_code:[0-9A-Fa-f]+}/mail')
    config.add_route('01-ticket-reset-scans',           '/0.1/tickets/resetscans')
    return config